package com.YiNong.WebService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-12-01T18:44:33.884+08:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://app.118328/", name = "AppAgentSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface AppAgentSoap {

    @WebResult(name = "UserBindingResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "UserBinding", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.UserBinding")
    @WebMethod(operationName = "UserBinding", action = "http://app.118328/UserBinding")
    @ResponseWrapper(localName = "UserBindingResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.UserBindingResponse")
    public java.lang.String userBinding(
        @WebParam(name = "msg", targetNamespace = "http://app.118328/")
        java.lang.String msg
    );

    @WebResult(name = "GetQGInfoResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetQGInfo", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetQGInfo")
    @WebMethod(operationName = "GetQGInfo", action = "http://app.118328/GetQGInfo")
    @ResponseWrapper(localName = "GetQGInfoResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetQGInfoResponse")
    public java.lang.String getQGInfo(
        @WebParam(name = "Id", targetNamespace = "http://app.118328/")
        int id
    );

    @WebResult(name = "GetTownListResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetTownList", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetTownList")
    @WebMethod(operationName = "GetTownList", action = "http://app.118328/GetTownList")
    @ResponseWrapper(localName = "GetTownListResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetTownListResponse")
    public java.lang.String getTownList(
        @WebParam(name = "Pageindex", targetNamespace = "http://app.118328/")
        int pageindex,
        @WebParam(name = "Pagesize", targetNamespace = "http://app.118328/")
        int pagesize
    );

    @WebResult(name = "CreateUserResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "CreateUser", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.CreateUser")
    @WebMethod(operationName = "CreateUser", action = "http://app.118328/CreateUser")
    @ResponseWrapper(localName = "CreateUserResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.CreateUserResponse")
    public java.lang.String createUser(
        @WebParam(name = "msg", targetNamespace = "http://app.118328/")
        java.lang.String msg
    );

    @WebResult(name = "GetWDInfoResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetWDInfo", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetWDInfo")
    @WebMethod(operationName = "GetWDInfo", action = "http://app.118328/GetWDInfo")
    @ResponseWrapper(localName = "GetWDInfoResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetWDInfoResponse")
    public java.lang.String getWDInfo(
        @WebParam(name = "id", targetNamespace = "http://app.118328/")
        int id
    );

    @WebResult(name = "GetVideoListResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetVideoList", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetVideoList")
    @WebMethod(operationName = "GetVideoList", action = "http://app.118328/GetVideoList")
    @ResponseWrapper(localName = "GetVideoListResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetVideoListResponse")
    public java.lang.String getVideoList(
        @WebParam(name = "Pageindex", targetNamespace = "http://app.118328/")
        int pageindex,
        @WebParam(name = "Pagesize", targetNamespace = "http://app.118328/")
        int pagesize,
        @WebParam(name = "startdate", targetNamespace = "http://app.118328/")
        java.lang.String startdate,
        @WebParam(name = "enddate", targetNamespace = "http://app.118328/")
        java.lang.String enddate
    );

    @WebResult(name = "GetGYInfoResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetGYInfo", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetGYInfo")
    @WebMethod(operationName = "GetGYInfo", action = "http://app.118328/GetGYInfo")
    @ResponseWrapper(localName = "GetGYInfoResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetGYInfoResponse")
    public java.lang.String getGYInfo(
        @WebParam(name = "Id", targetNamespace = "http://app.118328/")
        int id
    );

    @WebResult(name = "GetQZInfoResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetQZInfo", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetQZInfo")
    @WebMethod(operationName = "GetQZInfo", action = "http://app.118328/GetQZInfo")
    @ResponseWrapper(localName = "GetQZInfoResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetQZInfoResponse")
    public java.lang.String getQZInfo(
        @WebParam(name = "Id", targetNamespace = "http://app.118328/")
        int id
    );

    @WebResult(name = "GetWTListResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetWTList", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetWTList")
    @WebMethod(operationName = "GetWTList", action = "http://app.118328/GetWTList")
    @ResponseWrapper(localName = "GetWTListResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetWTListResponse")
    public java.lang.String getWTList(
        @WebParam(name = "Pageindex", targetNamespace = "http://app.118328/")
        int pageindex,
        @WebParam(name = "Pagesize", targetNamespace = "http://app.118328/")
        int pagesize,
        @WebParam(name = "quest_catalog_id", targetNamespace = "http://app.118328/")
        int questCatalogId,
        @WebParam(name = "startdate", targetNamespace = "http://app.118328/")
        java.lang.String startdate,
        @WebParam(name = "enddate", targetNamespace = "http://app.118328/")
        java.lang.String enddate
    );

    @WebResult(name = "GetTownNewsListResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetTownNewsList", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetTownNewsList")
    @WebMethod(operationName = "GetTownNewsList", action = "http://app.118328/GetTownNewsList")
    @ResponseWrapper(localName = "GetTownNewsListResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetTownNewsListResponse")
    public java.lang.String getTownNewsList(
        @WebParam(name = "PlaceId", targetNamespace = "http://app.118328/")
        int placeId
    );

    @WebResult(name = "GetEntListResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetEntList", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetEntList")
    @WebMethod(operationName = "GetEntList", action = "http://app.118328/GetEntList")
    @ResponseWrapper(localName = "GetEntListResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetEntListResponse")
    public java.lang.String getEntList(
        @WebParam(name = "Pageindex", targetNamespace = "http://app.118328/")
        int pageindex,
        @WebParam(name = "Pagesize", targetNamespace = "http://app.118328/")
        int pagesize,
        @WebParam(name = "startdate", targetNamespace = "http://app.118328/")
        java.lang.String startdate,
        @WebParam(name = "enddate", targetNamespace = "http://app.118328/")
        java.lang.String enddate
    );

    @WebResult(name = "GetZPInfoResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetZPInfo", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetZPInfo")
    @WebMethod(operationName = "GetZPInfo", action = "http://app.118328/GetZPInfo")
    @ResponseWrapper(localName = "GetZPInfoResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetZPInfoResponse")
    public java.lang.String getZPInfo(
        @WebParam(name = "Id", targetNamespace = "http://app.118328/")
        int id
    );

    @WebResult(name = "GetZPListResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetZPList", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetZPList")
    @WebMethod(operationName = "GetZPList", action = "http://app.118328/GetZPList")
    @ResponseWrapper(localName = "GetZPListResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetZPListResponse")
    public java.lang.String getZPList(
        @WebParam(name = "Pageindex", targetNamespace = "http://app.118328/")
        int pageindex,
        @WebParam(name = "Pagesize", targetNamespace = "http://app.118328/")
        int pagesize,
        @WebParam(name = "catalog_id", targetNamespace = "http://app.118328/")
        int catalogId,
        @WebParam(name = "startdate", targetNamespace = "http://app.118328/")
        java.lang.String startdate,
        @WebParam(name = "enddate", targetNamespace = "http://app.118328/")
        java.lang.String enddate
    );

    @WebResult(name = "GetEntInfoResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetEntInfo", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetEntInfo")
    @WebMethod(operationName = "GetEntInfo", action = "http://app.118328/GetEntInfo")
    @ResponseWrapper(localName = "GetEntInfoResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetEntInfoResponse")
    public java.lang.String getEntInfo(
        @WebParam(name = "Id", targetNamespace = "http://app.118328/")
        int id
    );

    @WebResult(name = "GetVideoInfoResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetVideoInfo", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetVideoInfo")
    @WebMethod(operationName = "GetVideoInfo", action = "http://app.118328/GetVideoInfo")
    @ResponseWrapper(localName = "GetVideoInfoResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetVideoInfoResponse")
    public java.lang.String getVideoInfo(
        @WebParam(name = "id", targetNamespace = "http://app.118328/")
        int id
    );

    @WebResult(name = "GetNewsListResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetNewsList", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetNewsList")
    @WebMethod(operationName = "GetNewsList", action = "http://app.118328/GetNewsList")
    @ResponseWrapper(localName = "GetNewsListResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetNewsListResponse")
    public java.lang.String getNewsList(
        @WebParam(name = "Pageindex", targetNamespace = "http://app.118328/")
        int pageindex,
        @WebParam(name = "Pagesize", targetNamespace = "http://app.118328/")
        int pagesize,
        @WebParam(name = "startdate", targetNamespace = "http://app.118328/")
        java.lang.String startdate,
        @WebParam(name = "enddate", targetNamespace = "http://app.118328/")
        java.lang.String enddate
    );

    @WebResult(name = "GetAppListResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetAppList", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetAppList")
    @WebMethod(operationName = "GetAppList", action = "http://app.118328/GetAppList")
    @ResponseWrapper(localName = "GetAppListResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetAppListResponse")
    public java.lang.String getAppList(
        @WebParam(name = "page", targetNamespace = "http://app.118328/")
        int page,
        @WebParam(name = "limit", targetNamespace = "http://app.118328/")
        int limit,
        @WebParam(name = "keyWord", targetNamespace = "http://app.118328/")
        java.lang.String keyWord
    );

    @WebResult(name = "GetTowPicListResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetTowPicList", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetTowPicList")
    @WebMethod(operationName = "GetTowPicList", action = "http://app.118328/GetTowPicList")
    @ResponseWrapper(localName = "GetTowPicListResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetTowPicListResponse")
    public java.lang.String getTowPicList(
        @WebParam(name = "PlaceId", targetNamespace = "http://app.118328/")
        int placeId
    );

    @WebResult(name = "GetTownSpecialtyListResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetTownSpecialtyList", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetTownSpecialtyList")
    @WebMethod(operationName = "GetTownSpecialtyList", action = "http://app.118328/GetTownSpecialtyList")
    @ResponseWrapper(localName = "GetTownSpecialtyListResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetTownSpecialtyListResponse")
    public java.lang.String getTownSpecialtyList(
        @WebParam(name = "Ht_Id", targetNamespace = "http://app.118328/")
        int htId
    );

    @WebResult(name = "GetQGListResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetQGList", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetQGList")
    @WebMethod(operationName = "GetQGList", action = "http://app.118328/GetQGList")
    @ResponseWrapper(localName = "GetQGListResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetQGListResponse")
    public java.lang.String getQGList(
        @WebParam(name = "Pageindex", targetNamespace = "http://app.118328/")
        int pageindex,
        @WebParam(name = "Pagesize", targetNamespace = "http://app.118328/")
        int pagesize,
        @WebParam(name = "Status", targetNamespace = "http://app.118328/")
        int status,
        @WebParam(name = "startdate", targetNamespace = "http://app.118328/")
        java.lang.String startdate,
        @WebParam(name = "enddate", targetNamespace = "http://app.118328/")
        java.lang.String enddate
    );

    @WebResult(name = "GetQZListResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetQZList", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetQZList")
    @WebMethod(operationName = "GetQZList", action = "http://app.118328/GetQZList")
    @ResponseWrapper(localName = "GetQZListResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetQZListResponse")
    public java.lang.String getQZList(
        @WebParam(name = "Pageindex", targetNamespace = "http://app.118328/")
        int pageindex,
        @WebParam(name = "Pagesize", targetNamespace = "http://app.118328/")
        int pagesize,
        @WebParam(name = "catalog_id", targetNamespace = "http://app.118328/")
        int catalogId,
        @WebParam(name = "startdate", targetNamespace = "http://app.118328/")
        java.lang.String startdate,
        @WebParam(name = "enddate", targetNamespace = "http://app.118328/")
        java.lang.String enddate
    );

    @WebResult(name = "UserLoginResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "UserLogin", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.UserLogin")
    @WebMethod(operationName = "UserLogin", action = "http://app.118328/UserLogin")
    @ResponseWrapper(localName = "UserLoginResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.UserLoginResponse")
    public java.lang.String userLogin(
        @WebParam(name = "msg", targetNamespace = "http://app.118328/")
        java.lang.String msg
    );

    @WebResult(name = "GetTownFarmhouseListResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetTownFarmhouseList", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetTownFarmhouseList")
    @WebMethod(operationName = "GetTownFarmhouseList", action = "http://app.118328/GetTownFarmhouseList")
    @ResponseWrapper(localName = "GetTownFarmhouseListResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetTownFarmhouseListResponse")
    public java.lang.String getTownFarmhouseList(
        @WebParam(name = "Ht_Id", targetNamespace = "http://app.118328/")
        int htId
    );

    @WebResult(name = "GetGYListResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetGYList", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetGYList")
    @WebMethod(operationName = "GetGYList", action = "http://app.118328/GetGYList")
    @ResponseWrapper(localName = "GetGYListResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetGYListResponse")
    public java.lang.String getGYList(
        @WebParam(name = "Pageindex", targetNamespace = "http://app.118328/")
        int pageindex,
        @WebParam(name = "Pagesize", targetNamespace = "http://app.118328/")
        int pagesize,
        @WebParam(name = "startdate", targetNamespace = "http://app.118328/")
        java.lang.String startdate,
        @WebParam(name = "enddate", targetNamespace = "http://app.118328/")
        java.lang.String enddate
    );
}
