
package com.YiNong.WebService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-12-01T18:44:33.795+08:00
 * Generated source version: 2.7.0
 * 
 */
public final class AppAgentSoap_AppAgentSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://app.118328/", "AppAgent");

    private AppAgentSoap_AppAgentSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AppAgent.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AppAgent ss = new AppAgent(wsdlURL, SERVICE_NAME);
        AppAgentSoap port = ss.getAppAgentSoap12();  
        
        {
        System.out.println("Invoking userBinding...");
        java.lang.String _userBinding_msg = "";
        java.lang.String _userBinding__return = port.userBinding(_userBinding_msg);
        System.out.println("userBinding.result=" + _userBinding__return);


        }
        {
        System.out.println("Invoking getQGInfo...");
        int _getQGInfo_id = 0;
        java.lang.String _getQGInfo__return = port.getQGInfo(_getQGInfo_id);
        System.out.println("getQGInfo.result=" + _getQGInfo__return);


        }
        {
        System.out.println("Invoking getTownList...");
        int _getTownList_pageindex = 0;
        int _getTownList_pagesize = 0;
        java.lang.String _getTownList__return = port.getTownList(_getTownList_pageindex, _getTownList_pagesize);
        System.out.println("getTownList.result=" + _getTownList__return);


        }
        {
        System.out.println("Invoking createUser...");
        java.lang.String _createUser_msg = "";
        java.lang.String _createUser__return = port.createUser(_createUser_msg);
        System.out.println("createUser.result=" + _createUser__return);


        }
        {
        System.out.println("Invoking getWDInfo...");
        int _getWDInfo_id = 0;
        java.lang.String _getWDInfo__return = port.getWDInfo(_getWDInfo_id);
        System.out.println("getWDInfo.result=" + _getWDInfo__return);


        }
        {
        System.out.println("Invoking getVideoList...");
        int _getVideoList_pageindex = 0;
        int _getVideoList_pagesize = 0;
        java.lang.String _getVideoList_startdate = "";
        java.lang.String _getVideoList_enddate = "";
        java.lang.String _getVideoList__return = port.getVideoList(_getVideoList_pageindex, _getVideoList_pagesize, _getVideoList_startdate, _getVideoList_enddate);
        System.out.println("getVideoList.result=" + _getVideoList__return);


        }
        {
        System.out.println("Invoking getGYInfo...");
        int _getGYInfo_id = 0;
        java.lang.String _getGYInfo__return = port.getGYInfo(_getGYInfo_id);
        System.out.println("getGYInfo.result=" + _getGYInfo__return);


        }
        {
        System.out.println("Invoking getQZInfo...");
        int _getQZInfo_id = 0;
        java.lang.String _getQZInfo__return = port.getQZInfo(_getQZInfo_id);
        System.out.println("getQZInfo.result=" + _getQZInfo__return);


        }
        {
        System.out.println("Invoking getWTList...");
        int _getWTList_pageindex = 0;
        int _getWTList_pagesize = 0;
        int _getWTList_questCatalogId = 0;
        java.lang.String _getWTList_startdate = "";
        java.lang.String _getWTList_enddate = "";
        java.lang.String _getWTList__return = port.getWTList(_getWTList_pageindex, _getWTList_pagesize, _getWTList_questCatalogId, _getWTList_startdate, _getWTList_enddate);
        System.out.println("getWTList.result=" + _getWTList__return);


        }
        {
        System.out.println("Invoking getTownNewsList...");
        int _getTownNewsList_placeId = 0;
        java.lang.String _getTownNewsList__return = port.getTownNewsList(_getTownNewsList_placeId);
        System.out.println("getTownNewsList.result=" + _getTownNewsList__return);


        }
        {
        System.out.println("Invoking getEntList...");
        int _getEntList_pageindex = 0;
        int _getEntList_pagesize = 0;
        java.lang.String _getEntList_startdate = "";
        java.lang.String _getEntList_enddate = "";
        java.lang.String _getEntList__return = port.getEntList(_getEntList_pageindex, _getEntList_pagesize, _getEntList_startdate, _getEntList_enddate);
        System.out.println("getEntList.result=" + _getEntList__return);


        }
        {
        System.out.println("Invoking getZPInfo...");
        int _getZPInfo_id = 0;
        java.lang.String _getZPInfo__return = port.getZPInfo(_getZPInfo_id);
        System.out.println("getZPInfo.result=" + _getZPInfo__return);


        }
        {
        System.out.println("Invoking getZPList...");
        int _getZPList_pageindex = 0;
        int _getZPList_pagesize = 0;
        int _getZPList_catalogId = 0;
        java.lang.String _getZPList_startdate = "";
        java.lang.String _getZPList_enddate = "";
        java.lang.String _getZPList__return = port.getZPList(_getZPList_pageindex, _getZPList_pagesize, _getZPList_catalogId, _getZPList_startdate, _getZPList_enddate);
        System.out.println("getZPList.result=" + _getZPList__return);


        }
        {
        System.out.println("Invoking getEntInfo...");
        int _getEntInfo_id = 0;
        java.lang.String _getEntInfo__return = port.getEntInfo(_getEntInfo_id);
        System.out.println("getEntInfo.result=" + _getEntInfo__return);


        }
        {
        System.out.println("Invoking getVideoInfo...");
        int _getVideoInfo_id = 0;
        java.lang.String _getVideoInfo__return = port.getVideoInfo(_getVideoInfo_id);
        System.out.println("getVideoInfo.result=" + _getVideoInfo__return);


        }
        {
        System.out.println("Invoking getNewsList...");
        int _getNewsList_pageindex = 0;
        int _getNewsList_pagesize = 0;
        java.lang.String _getNewsList_startdate = "";
        java.lang.String _getNewsList_enddate = "";
        java.lang.String _getNewsList__return = port.getNewsList(_getNewsList_pageindex, _getNewsList_pagesize, _getNewsList_startdate, _getNewsList_enddate);
        System.out.println("getNewsList.result=" + _getNewsList__return);


        }
        {
        System.out.println("Invoking getAppList...");
        int _getAppList_page = 0;
        int _getAppList_limit = 0;
        java.lang.String _getAppList_keyWord = "";
        java.lang.String _getAppList__return = port.getAppList(_getAppList_page, _getAppList_limit, _getAppList_keyWord);
        System.out.println("getAppList.result=" + _getAppList__return);


        }
        {
        System.out.println("Invoking getTowPicList...");
        int _getTowPicList_placeId = 0;
        java.lang.String _getTowPicList__return = port.getTowPicList(_getTowPicList_placeId);
        System.out.println("getTowPicList.result=" + _getTowPicList__return);


        }
        {
        System.out.println("Invoking getTownSpecialtyList...");
        int _getTownSpecialtyList_htId = 0;
        java.lang.String _getTownSpecialtyList__return = port.getTownSpecialtyList(_getTownSpecialtyList_htId);
        System.out.println("getTownSpecialtyList.result=" + _getTownSpecialtyList__return);


        }
        {
        System.out.println("Invoking getQGList...");
        int _getQGList_pageindex = 0;
        int _getQGList_pagesize = 0;
        int _getQGList_status = 0;
        java.lang.String _getQGList_startdate = "";
        java.lang.String _getQGList_enddate = "";
        java.lang.String _getQGList__return = port.getQGList(_getQGList_pageindex, _getQGList_pagesize, _getQGList_status, _getQGList_startdate, _getQGList_enddate);
        System.out.println("getQGList.result=" + _getQGList__return);


        }
        {
        System.out.println("Invoking getQZList...");
        int _getQZList_pageindex = 0;
        int _getQZList_pagesize = 0;
        int _getQZList_catalogId = 0;
        java.lang.String _getQZList_startdate = "";
        java.lang.String _getQZList_enddate = "";
        java.lang.String _getQZList__return = port.getQZList(_getQZList_pageindex, _getQZList_pagesize, _getQZList_catalogId, _getQZList_startdate, _getQZList_enddate);
        System.out.println("getQZList.result=" + _getQZList__return);


        }
        {
        System.out.println("Invoking userLogin...");
        java.lang.String _userLogin_msg = "";
        java.lang.String _userLogin__return = port.userLogin(_userLogin_msg);
        System.out.println("userLogin.result=" + _userLogin__return);


        }
        {
        System.out.println("Invoking getTownFarmhouseList...");
        int _getTownFarmhouseList_htId = 0;
        java.lang.String _getTownFarmhouseList__return = port.getTownFarmhouseList(_getTownFarmhouseList_htId);
        System.out.println("getTownFarmhouseList.result=" + _getTownFarmhouseList__return);


        }
        {
        System.out.println("Invoking getGYList...");
        int _getGYList_pageindex = 0;
        int _getGYList_pagesize = 0;
        java.lang.String _getGYList_startdate = "";
        java.lang.String _getGYList_enddate = "";
        java.lang.String _getGYList__return = port.getGYList(_getGYList_pageindex, _getGYList_pagesize, _getGYList_startdate, _getGYList_enddate);
        System.out.println("getGYList.result=" + _getGYList__return);


        }

        System.exit(0);
    }

}
