package com.YiNong.WebService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2012-12-14T19:26:52.007+08:00
 * Generated source version: 2.7.1
 * 
 */
@WebService(targetNamespace = "http://app.118328/", name = "AppAgentSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface AppAgentSoap {

    @WebResult(name = "GetGYInfoResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetGYInfo", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetGYInfo")
    @WebMethod(operationName = "GetGYInfo", action = "http://app.118328/GetGYInfo")
    @ResponseWrapper(localName = "GetGYInfoResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetGYInfoResponse")
    public java.lang.String getGYInfo(
        @WebParam(name = "Id", targetNamespace = "http://app.118328/")
        int id
    );

    @WebResult(name = "AddQGResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "AddQG", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.AddQG")
    @WebMethod(operationName = "AddQG", action = "http://app.118328/AddQG")
    @ResponseWrapper(localName = "AddQGResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.AddQGResponse")
    public java.lang.String addQG(
        @WebParam(name = "mid", targetNamespace = "http://app.118328/")
        int mid,
        @WebParam(name = "product_name", targetNamespace = "http://app.118328/")
        java.lang.String productName,
        @WebParam(name = "low_price", targetNamespace = "http://app.118328/")
        double lowPrice,
        @WebParam(name = "high_price", targetNamespace = "http://app.118328/")
        double highPrice,
        @WebParam(name = "is_discuss", targetNamespace = "http://app.118328/")
        java.lang.String isDiscuss,
        @WebParam(name = "product_desc", targetNamespace = "http://app.118328/")
        java.lang.String productDesc,
        @WebParam(name = "begin_time", targetNamespace = "http://app.118328/")
        javax.xml.datatype.XMLGregorianCalendar beginTime,
        @WebParam(name = "end_time", targetNamespace = "http://app.118328/")
        javax.xml.datatype.XMLGregorianCalendar endTime,
        @WebParam(name = "contact_phone", targetNamespace = "http://app.118328/")
        java.lang.String contactPhone,
        @WebParam(name = "contact_name", targetNamespace = "http://app.118328/")
        java.lang.String contactName
    );

    @WebResult(name = "UserBindingResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "UserBinding", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.UserBinding")
    @WebMethod(operationName = "UserBinding", action = "http://app.118328/UserBinding")
    @ResponseWrapper(localName = "UserBindingResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.UserBindingResponse")
    public java.lang.String userBinding(
        @WebParam(name = "msg", targetNamespace = "http://app.118328/")
        java.lang.String msg
    );

    @WebResult(name = "GetQGInfoResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetQGInfo", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetQGInfo")
    @WebMethod(operationName = "GetQGInfo", action = "http://app.118328/GetQGInfo")
    @ResponseWrapper(localName = "GetQGInfoResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetQGInfoResponse")
    public java.lang.String getQGInfo(
        @WebParam(name = "Id", targetNamespace = "http://app.118328/")
        int id
    );

    @WebResult(name = "AddGYResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "AddGY", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.AddGY")
    @WebMethod(operationName = "AddGY", action = "http://app.118328/AddGY")
    @ResponseWrapper(localName = "AddGYResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.AddGYResponse")
    public java.lang.String addGY(
        @WebParam(name = "mid", targetNamespace = "http://app.118328/")
        int mid,
        @WebParam(name = "product_name", targetNamespace = "http://app.118328/")
        java.lang.String productName,
        @WebParam(name = "low_price", targetNamespace = "http://app.118328/")
        double lowPrice,
        @WebParam(name = "high_price", targetNamespace = "http://app.118328/")
        double highPrice,
        @WebParam(name = "is_discuss", targetNamespace = "http://app.118328/")
        java.lang.String isDiscuss,
        @WebParam(name = "product_place_id", targetNamespace = "http://app.118328/")
        int productPlaceId,
        @WebParam(name = "product_desc", targetNamespace = "http://app.118328/")
        java.lang.String productDesc,
        @WebParam(name = "begin_time", targetNamespace = "http://app.118328/")
        javax.xml.datatype.XMLGregorianCalendar beginTime,
        @WebParam(name = "end_time", targetNamespace = "http://app.118328/")
        javax.xml.datatype.XMLGregorianCalendar endTime,
        @WebParam(name = "contact_phone", targetNamespace = "http://app.118328/")
        java.lang.String contactPhone,
        @WebParam(name = "contact_name", targetNamespace = "http://app.118328/")
        java.lang.String contactName
    );

    @WebResult(name = "AddZPResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "AddZP", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.AddZP")
    @WebMethod(operationName = "AddZP", action = "http://app.118328/AddZP")
    @ResponseWrapper(localName = "AddZPResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.AddZPResponse")
    public java.lang.String addZP(
        @WebParam(name = "mid", targetNamespace = "http://app.118328/")
        int mid,
        @WebParam(name = "job_catalog_id", targetNamespace = "http://app.118328/")
        int jobCatalogId,
        @WebParam(name = "job_attr", targetNamespace = "http://app.118328/")
        java.lang.String jobAttr,
        @WebParam(name = "work_years", targetNamespace = "http://app.118328/")
        int workYears,
        @WebParam(name = "low_price", targetNamespace = "http://app.118328/")
        double lowPrice,
        @WebParam(name = "hight_price", targetNamespace = "http://app.118328/")
        double hightPrice,
        @WebParam(name = "is_discuss", targetNamespace = "http://app.118328/")
        java.lang.String isDiscuss,
        @WebParam(name = "recruit_num", targetNamespace = "http://app.118328/")
        int recruitNum,
        @WebParam(name = "job_place_id", targetNamespace = "http://app.118328/")
        int jobPlaceId,
        @WebParam(name = "job_desc", targetNamespace = "http://app.118328/")
        java.lang.String jobDesc,
        @WebParam(name = "begin_time", targetNamespace = "http://app.118328/")
        javax.xml.datatype.XMLGregorianCalendar beginTime,
        @WebParam(name = "end_time", targetNamespace = "http://app.118328/")
        javax.xml.datatype.XMLGregorianCalendar endTime,
        @WebParam(name = "corp_name", targetNamespace = "http://app.118328/")
        java.lang.String corpName,
        @WebParam(name = "contact_name", targetNamespace = "http://app.118328/")
        java.lang.String contactName,
        @WebParam(name = "contact_phone", targetNamespace = "http://app.118328/")
        java.lang.String contactPhone
    );

    @WebResult(name = "GetTownListResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetTownList", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetTownList")
    @WebMethod(operationName = "GetTownList", action = "http://app.118328/GetTownList")
    @ResponseWrapper(localName = "GetTownListResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetTownListResponse")
    public java.lang.String getTownList(
        @WebParam(name = "Pageindex", targetNamespace = "http://app.118328/")
        int pageindex,
        @WebParam(name = "Pagesize", targetNamespace = "http://app.118328/")
        int pagesize
    );

    @WebResult(name = "CreateUserResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "CreateUser", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.CreateUser")
    @WebMethod(operationName = "CreateUser", action = "http://app.118328/CreateUser")
    @ResponseWrapper(localName = "CreateUserResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.CreateUserResponse")
    public java.lang.String createUser(
        @WebParam(name = "msg", targetNamespace = "http://app.118328/")
        java.lang.String msg
    );

    @WebResult(name = "GetWDInfoResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetWDInfo", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetWDInfo")
    @WebMethod(operationName = "GetWDInfo", action = "http://app.118328/GetWDInfo")
    @ResponseWrapper(localName = "GetWDInfoResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetWDInfoResponse")
    public java.lang.String getWDInfo(
        @WebParam(name = "id", targetNamespace = "http://app.118328/")
        int id
    );

    @WebResult(name = "GetVideoListResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetVideoList", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetVideoList")
    @WebMethod(operationName = "GetVideoList", action = "http://app.118328/GetVideoList")
    @ResponseWrapper(localName = "GetVideoListResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetVideoListResponse")
    public java.lang.String getVideoList(
        @WebParam(name = "Pageindex", targetNamespace = "http://app.118328/")
        int pageindex,
        @WebParam(name = "Pagesize", targetNamespace = "http://app.118328/")
        int pagesize,
        @WebParam(name = "startdate", targetNamespace = "http://app.118328/")
        java.lang.String startdate,
        @WebParam(name = "enddate", targetNamespace = "http://app.118328/")
        java.lang.String enddate
    );

    @WebResult(name = "GetQZInfoResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetQZInfo", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetQZInfo")
    @WebMethod(operationName = "GetQZInfo", action = "http://app.118328/GetQZInfo")
    @ResponseWrapper(localName = "GetQZInfoResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetQZInfoResponse")
    public java.lang.String getQZInfo(
        @WebParam(name = "Id", targetNamespace = "http://app.118328/")
        int id
    );

    @WebResult(name = "GetWTListResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetWTList", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetWTList")
    @WebMethod(operationName = "GetWTList", action = "http://app.118328/GetWTList")
    @ResponseWrapper(localName = "GetWTListResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetWTListResponse")
    public java.lang.String getWTList(
        @WebParam(name = "Pageindex", targetNamespace = "http://app.118328/")
        int pageindex,
        @WebParam(name = "Pagesize", targetNamespace = "http://app.118328/")
        int pagesize,
        @WebParam(name = "quest_catalog_id", targetNamespace = "http://app.118328/")
        int questCatalogId,
        @WebParam(name = "startdate", targetNamespace = "http://app.118328/")
        java.lang.String startdate,
        @WebParam(name = "enddate", targetNamespace = "http://app.118328/")
        java.lang.String enddate
    );

    @WebResult(name = "GetTownNewsListResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetTownNewsList", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetTownNewsList")
    @WebMethod(operationName = "GetTownNewsList", action = "http://app.118328/GetTownNewsList")
    @ResponseWrapper(localName = "GetTownNewsListResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetTownNewsListResponse")
    public java.lang.String getTownNewsList(
        @WebParam(name = "PlaceId", targetNamespace = "http://app.118328/")
        int placeId
    );

    @WebResult(name = "GetEntListResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetEntList", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetEntList")
    @WebMethod(operationName = "GetEntList", action = "http://app.118328/GetEntList")
    @ResponseWrapper(localName = "GetEntListResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetEntListResponse")
    public java.lang.String getEntList(
        @WebParam(name = "Pageindex", targetNamespace = "http://app.118328/")
        int pageindex,
        @WebParam(name = "Pagesize", targetNamespace = "http://app.118328/")
        int pagesize,
        @WebParam(name = "startdate", targetNamespace = "http://app.118328/")
        java.lang.String startdate,
        @WebParam(name = "enddate", targetNamespace = "http://app.118328/")
        java.lang.String enddate
    );

    @WebResult(name = "GetEntInfoResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetEntInfo", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetEntInfo")
    @WebMethod(operationName = "GetEntInfo", action = "http://app.118328/GetEntInfo")
    @ResponseWrapper(localName = "GetEntInfoResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetEntInfoResponse")
    public java.lang.String getEntInfo(
        @WebParam(name = "Id", targetNamespace = "http://app.118328/")
        int id
    );

    @WebResult(name = "GetNewsListResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetNewsList", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetNewsList")
    @WebMethod(operationName = "GetNewsList", action = "http://app.118328/GetNewsList")
    @ResponseWrapper(localName = "GetNewsListResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetNewsListResponse")
    public java.lang.String getNewsList(
        @WebParam(name = "Pageindex", targetNamespace = "http://app.118328/")
        int pageindex,
        @WebParam(name = "Pagesize", targetNamespace = "http://app.118328/")
        int pagesize,
        @WebParam(name = "startdate", targetNamespace = "http://app.118328/")
        java.lang.String startdate,
        @WebParam(name = "enddate", targetNamespace = "http://app.118328/")
        java.lang.String enddate
    );

    @WebResult(name = "GetVideoInfoResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetVideoInfo", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetVideoInfo")
    @WebMethod(operationName = "GetVideoInfo", action = "http://app.118328/GetVideoInfo")
    @ResponseWrapper(localName = "GetVideoInfoResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetVideoInfoResponse")
    public java.lang.String getVideoInfo(
        @WebParam(name = "id", targetNamespace = "http://app.118328/")
        int id
    );

    @WebResult(name = "GetTownSpecialtyListResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetTownSpecialtyList", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetTownSpecialtyList")
    @WebMethod(operationName = "GetTownSpecialtyList", action = "http://app.118328/GetTownSpecialtyList")
    @ResponseWrapper(localName = "GetTownSpecialtyListResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetTownSpecialtyListResponse")
    public java.lang.String getTownSpecialtyList(
        @WebParam(name = "Ht_Id", targetNamespace = "http://app.118328/")
        int htId
    );

    @WebResult(name = "GetQGListResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetQGList", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetQGList")
    @WebMethod(operationName = "GetQGList", action = "http://app.118328/GetQGList")
    @ResponseWrapper(localName = "GetQGListResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetQGListResponse")
    public java.lang.String getQGList(
        @WebParam(name = "Pageindex", targetNamespace = "http://app.118328/")
        int pageindex,
        @WebParam(name = "Pagesize", targetNamespace = "http://app.118328/")
        int pagesize,
        @WebParam(name = "Status", targetNamespace = "http://app.118328/")
        int status,
        @WebParam(name = "startdate", targetNamespace = "http://app.118328/")
        java.lang.String startdate,
        @WebParam(name = "enddate", targetNamespace = "http://app.118328/")
        java.lang.String enddate
    );

    @WebResult(name = "UserLoginResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "UserLogin", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.UserLogin")
    @WebMethod(operationName = "UserLogin", action = "http://app.118328/UserLogin")
    @ResponseWrapper(localName = "UserLoginResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.UserLoginResponse")
    public java.lang.String userLogin(
        @WebParam(name = "msg", targetNamespace = "http://app.118328/")
        java.lang.String msg
    );

    @WebResult(name = "GetGYListResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetGYList", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetGYList")
    @WebMethod(operationName = "GetGYList", action = "http://app.118328/GetGYList")
    @ResponseWrapper(localName = "GetGYListResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetGYListResponse")
    public java.lang.String getGYList(
        @WebParam(name = "Pageindex", targetNamespace = "http://app.118328/")
        int pageindex,
        @WebParam(name = "Pagesize", targetNamespace = "http://app.118328/")
        int pagesize,
        @WebParam(name = "startdate", targetNamespace = "http://app.118328/")
        java.lang.String startdate,
        @WebParam(name = "enddate", targetNamespace = "http://app.118328/")
        java.lang.String enddate
    );

    @WebResult(name = "GetZPInfoResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetZPInfo", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetZPInfo")
    @WebMethod(operationName = "GetZPInfo", action = "http://app.118328/GetZPInfo")
    @ResponseWrapper(localName = "GetZPInfoResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetZPInfoResponse")
    public java.lang.String getZPInfo(
        @WebParam(name = "Id", targetNamespace = "http://app.118328/")
        int id
    );

    @WebResult(name = "GetZPListResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetZPList", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetZPList")
    @WebMethod(operationName = "GetZPList", action = "http://app.118328/GetZPList")
    @ResponseWrapper(localName = "GetZPListResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetZPListResponse")
    public java.lang.String getZPList(
        @WebParam(name = "Pageindex", targetNamespace = "http://app.118328/")
        int pageindex,
        @WebParam(name = "Pagesize", targetNamespace = "http://app.118328/")
        int pagesize,
        @WebParam(name = "catalog_id", targetNamespace = "http://app.118328/")
        int catalogId,
        @WebParam(name = "startdate", targetNamespace = "http://app.118328/")
        java.lang.String startdate,
        @WebParam(name = "enddate", targetNamespace = "http://app.118328/")
        java.lang.String enddate
    );

    @WebResult(name = "GetAppListResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetAppList", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetAppList")
    @WebMethod(operationName = "GetAppList", action = "http://app.118328/GetAppList")
    @ResponseWrapper(localName = "GetAppListResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetAppListResponse")
    public java.lang.String getAppList(
        @WebParam(name = "page", targetNamespace = "http://app.118328/")
        int page,
        @WebParam(name = "limit", targetNamespace = "http://app.118328/")
        int limit,
        @WebParam(name = "keyWord", targetNamespace = "http://app.118328/")
        java.lang.String keyWord
    );

    @WebResult(name = "GetTowPicListResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetTowPicList", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetTowPicList")
    @WebMethod(operationName = "GetTowPicList", action = "http://app.118328/GetTowPicList")
    @ResponseWrapper(localName = "GetTowPicListResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetTowPicListResponse")
    public java.lang.String getTowPicList(
        @WebParam(name = "PlaceId", targetNamespace = "http://app.118328/")
        int placeId
    );

    @WebResult(name = "GetQZListResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetQZList", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetQZList")
    @WebMethod(operationName = "GetQZList", action = "http://app.118328/GetQZList")
    @ResponseWrapper(localName = "GetQZListResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetQZListResponse")
    public java.lang.String getQZList(
        @WebParam(name = "Pageindex", targetNamespace = "http://app.118328/")
        int pageindex,
        @WebParam(name = "Pagesize", targetNamespace = "http://app.118328/")
        int pagesize,
        @WebParam(name = "catalog_id", targetNamespace = "http://app.118328/")
        int catalogId,
        @WebParam(name = "startdate", targetNamespace = "http://app.118328/")
        java.lang.String startdate,
        @WebParam(name = "enddate", targetNamespace = "http://app.118328/")
        java.lang.String enddate
    );

    @WebResult(name = "AddQZResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "AddQZ", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.AddQZ")
    @WebMethod(operationName = "AddQZ", action = "http://app.118328/AddQZ")
    @ResponseWrapper(localName = "AddQZResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.AddQZResponse")
    public java.lang.String addQZ(
        @WebParam(name = "mid", targetNamespace = "http://app.118328/")
        int mid,
        @WebParam(name = "jobid", targetNamespace = "http://app.118328/")
        int jobid,
        @WebParam(name = "attrid", targetNamespace = "http://app.118328/")
        int attrid,
        @WebParam(name = "work_years", targetNamespace = "http://app.118328/")
        int workYears,
        @WebParam(name = "low_price", targetNamespace = "http://app.118328/")
        double lowPrice,
        @WebParam(name = "hight_price", targetNamespace = "http://app.118328/")
        double hightPrice,
        @WebParam(name = "jobplaceid", targetNamespace = "http://app.118328/")
        int jobplaceid,
        @WebParam(name = "job_desc", targetNamespace = "http://app.118328/")
        java.lang.String jobDesc,
        @WebParam(name = "begintime", targetNamespace = "http://app.118328/")
        javax.xml.datatype.XMLGregorianCalendar begintime,
        @WebParam(name = "endtime", targetNamespace = "http://app.118328/")
        javax.xml.datatype.XMLGregorianCalendar endtime,
        @WebParam(name = "contact_phone", targetNamespace = "http://app.118328/")
        java.lang.String contactPhone,
        @WebParam(name = "contact_name", targetNamespace = "http://app.118328/")
        java.lang.String contactName
    );

    @WebResult(name = "GetTownFarmhouseListResult", targetNamespace = "http://app.118328/")
    @RequestWrapper(localName = "GetTownFarmhouseList", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetTownFarmhouseList")
    @WebMethod(operationName = "GetTownFarmhouseList", action = "http://app.118328/GetTownFarmhouseList")
    @ResponseWrapper(localName = "GetTownFarmhouseListResponse", targetNamespace = "http://app.118328/", className = "com.YiNong.WebService.GetTownFarmhouseListResponse")
    public java.lang.String getTownFarmhouseList(
        @WebParam(name = "Ht_Id", targetNamespace = "http://app.118328/")
        int htId
    );
}
